CREATE TABLE CLNT_MASTER (
    CLIENT_NO VARCHAR2(6) PRIMARY KEY CHECK (CLIENT_NO LIKE 'C%'),
    NAME VARCHAR2(20) NOT NULL,
    ADDRESS_1 VARCHAR2(30),
    ADDRESS_2 VARCHAR2(30),
    CITY VARCHAR2(15),
    PINCODE VARCHAR2(8),
    STATE VARCHAR2(15),
    BAL_DUE NUMBER(10, 2)
);
