CREATE TABLE EMP (
    EMP_NO NUMBER(4) PRIMARY KEY,
    E_NAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIRE_DATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPT_NO NUMBER(2) REFERENCES DEPT(DEPT_NO)
);
