CREATE TABLE PRODUCT_MASTER (
    PRODUCT_NO VARCHAR2(6),
    DESCRIPTION VARCHAR2(15),
    PROFIT_PERCENT NUMBER(4, 2),
    UNIT_MEASURE VARCHAR2(10),
    QTY_ON_HAND NUMBER(8),
    REORDER NUMBER(8),
    SELL_PRICE NUMBER(8, 2),
    COST_PRICE NUMBER(8, 2)
);
