CREATE TABLE SALES_MASTER (
    SALESMAN_NO VARCHAR2(6) PRIMARY KEY CHECK (SALESMAN_NO LIKE 'S%'),
    SALESMAN_NAME VARCHAR2(20) NOT NULL,
    ADDRESS_1 VARCHAR2(30) NOT NULL,
    ADDRESS_2 VARCHAR2(30),
    CITY VARCHAR2(20),
    PINCODE NUMBER(8),
    STATE VARCHAR2(15),
    SAL_AMT NUMBER(8, 2) NOT NULL CHECK (SAL_AMT != 0),
    TGT_TO_GET NUMBER(6, 2) NOT NULL CHECK (TGT_TO_GET != 0),
    YTD_SALES NUMBER(6, 2) NOT NULL,
    REMARKS VARCHAR2(60)
);
