CREATE TABLE SALESMAN_MASTER (
    SALESMAN_NO VARCHAR2(6),
    SALESMAN_NAME VARCHAR2(20),
    ADDRESS_1 VARCHAR2(30),
    ADDRESS_2 VARCHAR2(30),
    CITY VARCHAR2(20),
    PINCODE NUMBER(8),
    STATE VARCHAR2(15),
    SAL_AMT NUMBER(8, 2),
    TGT_TO_GET NUMBER(6, 2),
    YTD_SALES NUMBER(6, 2),
    REMARKS VARCHAR2(60)
);
