CREATE TABLE SALES_ORDER_DETAILS (
    ORDER_NO VARCHAR2(6) REFERENCES SALES_ORDER(ORDER_NO),
    PRODUCT_NO VARCHAR2(6) REFERENCES PRO_MASTER(PRODUCT_NO),
    QTY_ORDERED NUMBER(8),
    QTY_DISP NUMBER(8),
    PRODUCT_RATE NUMBER(10, 2)
);
