/* Q-1:- */
SELECT PRODUCT_NO,SUM(QTY_DISP) FROM SALES_ORDER_DETAILS GROUP BY PRODUCT_NO HAVING SUM(QTY_DISP)>=6;
/* Q-2:- */
SELECT PRODUCT_NO,SUM(QTY_DISP) FROM SALES_ORDER_DETAILS GROUP BY PRODUCT_NO;
/* Q-3:- */SELECT PRODUCT_NO,AVG(QTY_DISP) FROM SALES_ORDER_DETAILS GROUP BY PRODUCT_NO HAVING MAX(PRODUCT_RATE)<=15000;
/* Q-4:- */
SELECT COUNT(CLIENT_NO) FROM SALES_ORDER WHERE TO_CHAR(ORDER_DATE,'MM')LIKE'06';
/* Q-5:- */
SELECT COUNT(DEPT_NO) FROM EMP GROUP BY DEPT_NO HAVING DEPT_NO=20;
/* Q-6:- */
SELECT DEPT_NO,COUNT(EMP_NO) FROM EMP GROUP BY DEPT_NO ;
/* Q-7:- */
SELECT E_NAME FROM EMP WHERE SAL IN(SELECT MAX(SAL) FROM EMP WHERE DEPT_NO=10);
/* Q-8:- */
SELECT * FROM PRODUCT_MASTER ORDER BY SELL_PRICE DESC;
/* Q-9:- */
SELECT ORDER_NO,DELY_DATE FROM SALES_ORDER ORDER BY DELY_DATE;
/* Q-10: */
SELECT E_NAME,HIRE_DATE FROM EMP ORDER BY HIRE_DATE;
