/* Q-1:- */

CREATE INDEX IDX_PROD ON PRO_MASTER (COST_PRICE);

/* Q-2:- */

CREATE SEQUENCE INV_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 10 MINVALUE 1 CYCLE CACHE 4 ORDER;

/* Q-3:- */

CREATE TABLE PR4C(SR_NO NUMBER(2), NAME VARCHAR(15));
INSERT INTO PR4C VALUES(INV_SEQ.NEXTVAL, 'USER1');
INSERT INTO PR4C VALUES(INV_SEQ.NEXTVAL, 'USER2');
INSERT INTO PR4C VALUES(INV_SEQ.NEXTVAL, 'USER3');
INSERT INTO PR4C VALUES(INV_SEQ.NEXTVAL, 'USER4');

/* Q-4:- */

CREATE SEQUENCE INV_SEQ1 INCREMENT BY -1 START WITH 10 MAXVALUE 10 MINVALUE 1 CACHE 4 ORDER;

/* Q-5:- */

CREATE TABLE PR4E(SR_NO NUMBER(2), NAME VARCHAR(15));
INSERT INTO PR4E VALUES(INV_SEQ1.NEXTVAL, 'USER10');
INSERT INTO PR4E VALUES(INV_SEQ1.NEXTVAL, 'USER9');
INSERT INTO PR4E VALUES(INV_SEQ1.NEXTVAL, 'USER8');
INSERT INTO PR4E VALUES(INV_SEQ1.NEXTVAL, 'USER7');

/* Q-6:- */

CREATE SYNONYM CLNT FOR CLIENT;

