/* Q-1:- */
SELECT * FROM EMP NATURAL JOIN DEPT WHERE DEPT_NO=20;
/* Q-2:- */
SELECT * FROM CLIENT NATURAL JOIN CLNT WHERE CLIENT_NO IN('C00001','C00003');
/* Q-3:- */
 SELECT * FROM EMP JOIN DEPT USING(DEPT_NO) WHERE DEPT_NO=10;
/* Q-4:- */
SELECT  * FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPT_NO=DEPT.DEPT_NO WHERE MGR=7698;
/* Q-5:- */
SELECT * FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPT_NO=DEPT.DEPT_NO;
/* Q-6:- */
SELECT * FROM EMP RIGHT OUTER JOIN DEPT ON EMP.DEPT_NO=DEPT.DEPT_NO;
/* Q-7:- */
SELECT * FROM SALES_ORDER LEFT OUTER JOIN CLIENT ON SALES_ORDER.CLIENT_NO=CLIENT.CLIENT_NO;
/* Q-8:- */
SELECT * FROM SALES_ORDER RIGHT OUTER JOIN CLIENT ON SALES_ORDER.CLIENT_NO=CLIENT.CLIENT_NO;
