/* Q-1:- */

GRANT SELECT, INSERT ON SALES_ORDER TO khush;
GRANT SELECT, INSERT ON SALES_ORDER_DETAILS TO khush;

/* Q-2:- */

GRANT INSERT,UPDATE,DELETE ON CLIENT_MASTER TO khush WITH GRANT OPTION;

/* Q-3:- */

GRANT SELECT,INSERT ON EMP TO khush;

/* Q-4:- */

REVOKE ALL ON SALES_ORDER_DETAILS FROM khush;
REVOKE ALL ON SALES_ORDER_DETAILS FROM khush;

/* Q-5:- */

REVOKE ALL ON EMP FROM khush;

/* Q-6:- */

REVOKE ALL ON CLIENT_MASTER FROM khush;

/* Q-7:- */

CREATE USER khush IDENTIFIED BY hehe32;

/* Q-8:- */

ALTER USER khush IDENTIFIED BY hehe;

/* Q-9:- */

DROP USER khush;